In [33]:
import pandas as pd 
from sklearn.preprocessing import LabelEncoder, OrdinalEncoder, OneHotEncoder,StandardScaler
from sklearn.impute import SimpleImputer
from sklearn.pipeline import Pipeline
from sklearn.linear_model import LogisticRegression

In [34]:
df = pd.read_csv(r"D:\py_machine_learning\datasets\covid_toy - covid_toy.csv")

print(df.head())

   age  gender  fever cough     city has_covid
0   60    Male  103.0  Mild  Kolkata        No
1   27    Male  100.0  Mild    Delhi       Yes
2   42    Male  101.0  Mild    Delhi        No
3   31  Female   98.0  Mild  Kolkata        No
4   65  Female  101.0  Mild   Mumbai        No

In [35]:
df["fever"] = df["fever"].fillna(df["fever"].mean())

x = df.drop("has_covid", axis=1)
y = df["has_covid"]

In [36]:
le = LabelEncoder()

x["gender"] = le.fit_transform(x["gender"])
x["city"] = le.fit_transform(x["city"])

x.head()

   age  gender  fever cough  city
0   60       1  103.0  Mild     2
1   27       1  100.0  Mild     1
2   42       1  101.0  Mild     1
3   31       0   98.0  Mild     2
4   65       0  101.0  Mild     3

In [37]:
oe = OrdinalEncoder(categories=[["Mild", "Strong"]])

x["cough"] = oe.fit_transform(x[["cough"]])

x.head()

   age  gender  fever  cough  city
0   60       1  103.0    0.0     2
1   27       1  100.0    0.0     1
2   42       1  101.0    0.0     1
3   31       0   98.0    0.0     2
4   65       0  101.0    0.0     3

In [38]:
ohe = OneHotEncoder(sparse_output=False)

ohe_encode = ohe.fit_transform(x[["gender", "city"]])

ohe_encode

array([[0., 1., 0., 0., 1., 0.],
       [0., 1., 0., 1., 0., 0.],
       [0., 1., 0., 1., 0., 0.],
       [1., 0., 0., 0., 1., 0.],
       [1., 0., 0., 0., 0., 1.],
       [1., 0., 1., 0., 0., 0.],
       [0., 1., 1., 0., 0., 0.],
       [1., 0., 0., 0., 0., 1.],
       [1., 0., 1., 0., 0., 0.],
       [1., 0., 0., 1., 0., 0.],
       [1., 0., 0., 1., 0., 0.],
       [1., 0., 0., 0., 0., 1.],
       [1., 0., 0., 0., 1., 0.],
       [0., 1., 1., 0., 0., 0.],
       [0., 1., 1., 0., 0., 0.],
       [0., 1., 0., 0., 1., 0.],
       [1., 0., 0., 0., 1., 0.],
       [1., 0., 0., 1., 0., 0.],
       [1., 0., 1., 0., 0., 0.],
       [1., 0., 1., 0., 0., 0.],
       [0., 1., 1., 0., 0., 0.],
       [0., 1., 1., 0., 0., 0.],
       [1., 0., 0., 0., 1., 0.],
       [1., 0., 0., 1., 0., 0.],
       [1., 0., 0., 0., 1., 0.],
       [0., 1., 0., 0., 0., 1.],
       [1., 0., 0., 0., 1., 0.],
       [1., 0., 0., 1., 0., 0.],
       [0., 1., 0., 0., 1., 0.],
       [1., 0., 0., 0., 0., 1.],
       [0., 1., 0., 1., 0., 0.],
       [0., 1., 0., 0., 1., 0.],
       [1., 0., 0., 1., 0., 0.],
       [1., 0., 0., 0., 1., 0.],
       [0., 1., 0., 0., 0., 1.],
       [1., 0., 1., 0., 0., 0.],
       [1., 0., 1., 0., 0., 0.],
       [0., 1., 0., 0., 1., 0.],
       [1., 0., 0., 1., 0., 0.],
       [1., 0., 0., 0., 1., 0.],
       [1., 0., 0., 1., 0., 0.],
       [0., 1., 0., 0., 1., 0.],
       [0., 1., 0., 1., 0., 0.],
       [1., 0., 1., 0., 0., 0.],
       [0., 1., 0., 1., 0., 0.],
       [0., 1., 1., 0., 0., 0.],
       [1., 0., 0., 0., 0., 1.],
       [1., 0., 1., 0., 0., 0.],
       [0., 1., 1., 0., 0., 0.],
       [0., 1., 0., 0., 0., 1.],
       [0., 1., 0., 1., 0., 0.],
       [1., 0., 0., 0., 1., 0.],
       [1., 0., 1., 0., 0., 0.],
       [0., 1., 0., 1., 0., 0.],
       [1., 0., 0., 0., 0., 1.],
       [1., 0., 0., 0., 0., 1.],
       [0., 1., 0., 0., 1., 0.],
       [1., 0., 1., 0., 0., 0.],
       [0., 1., 0., 0., 0., 1.],
       [1., 0., 0., 0., 1., 0.],
       [1., 0., 1., 0., 0., 0.],
       [1., 0., 0., 0., 0., 1.],
       [1., 0., 1., 0., 0., 0.],
       [0., 1., 1., 0., 0., 0.],
       [0., 1., 0., 0., 0., 1.],
       [1., 0., 1., 0., 0., 0.],
       [0., 1., 0., 0., 1., 0.],
       [0., 1., 1., 0., 0., 0.],
       [1., 0., 0., 0., 1., 0.],
       [1., 0., 0., 1., 0., 0.],
       [1., 0., 0., 1., 0., 0.],
       [1., 0., 0., 1., 0., 0.],
       [1., 0., 0., 0., 1., 0.],
       [0., 1., 0., 0., 1., 0.],
       [1., 0., 0., 1., 0., 0.],
       [0., 1., 0., 0., 1., 0.],
       [0., 1., 1., 0., 0., 0.],
       [1., 0., 0., 0., 1., 0.],
       [0., 1., 1., 0., 0., 0.],
       [1., 0., 0., 0., 1., 0.],
       [1., 0., 0., 0., 0., 1.],
       [0., 1., 0., 1., 0., 0.],
       [0., 1., 0., 0., 1., 0.],
       [1., 0., 0., 0., 1., 0.],
       [1., 0., 0., 0., 0., 1.],
       [1., 0., 1., 0., 0., 0.],
       [0., 1., 1., 0., 0., 0.],
       [0., 1., 1., 0., 0., 0.],
       [1., 0., 0., 0., 1., 0.],
       [0., 1., 1., 0., 0., 0.],
       [1., 0., 0., 1., 0., 0.],
       [0., 1., 0., 1., 0., 0.],
       [1., 0., 0., 0., 1., 0.],
       [0., 1., 0., 0., 1., 0.],
       [0., 1., 0., 0., 1., 0.],
       [1., 0., 1., 0., 0., 0.],
       [1., 0., 0., 0., 1., 0.],
       [1., 0., 1., 0., 0., 0.],
       [1., 0., 0., 0., 0., 1.],
       [1., 0., 0., 0., 1., 0.]])

In [39]:
dummy_df = pd.get_dummies(
    x,
    columns=["gender", "city"]
)
dummy_df.head()

   age  fever  cough  gender_0  gender_1  city_0  city_1  city_2  city_3
0   60  103.0    0.0     False      True   False   False    True   False
1   27  100.0    0.0     False      True   False    True   False   False
2   42  101.0    0.0     False      True   False    True   False   False
3   31   98.0    0.0      True     False   False   False    True   False
4   65  101.0    0.0      True     False   False   False   False    True

In [40]:
numeric_cols = ["age", "fever"]
ordinal_cols = ["cough"]
nominal_cols = ["gender", "city"]

In [ ]:

from sklearn.compose import ColumnTransformer

preprocessor = ColumnTransformer(
    transformers=[
        ("num", StandardScaler(), numeric_cols),
        ("ord", OrdinalEncoder(categories=oe), ordinal_cols),
        ("nom", OneHotEncoder(drop="first"), nominal_cols)
    ]
)

model = Pipeline([
    ("preprocessing", preprocessor),
    ("classifier", LogisticRegression())
])

model

Pipeline(steps=[('preprocessing',
                 ColumnTransformer(transformers=[('num', StandardScaler(),
                                                  ['age', 'fever']),
                                                 ('ord',
                                                  OrdinalEncoder(categories=OrdinalEncoder(categories=[['Mild',
                                                                                                        'Strong']])),
                                                  ['cough']),
                                                 ('nom',
                                                  OneHotEncoder(drop='first'),
                                                  ['gender', 'city'])])),
                ('classifier', LogisticRegression())])