In [15]:
import numpy as np 
import pandas as pd

In [16]:
df = pd.read_csv(r"D:\py_machine_learning\datasets\insurance - insurance.csv")
df

      age     sex     bmi  children smoker     region      charges
0      19  female  27.900         0    yes  southwest  16884.92400
1      18    male  33.770         1     no  southeast   1725.55230
2      28    male  33.000         3     no  southeast   4449.46200
3      33    male  22.705         0     no  northwest  21984.47061
4      32    male  28.880         0     no  northwest   3866.85520
...   ...     ...     ...       ...    ...        ...          ...
1333   50    male  30.970         3     no  northwest  10600.54830
1334   18  female  31.920         0     no  northeast   2205.98080
1335   18  female  36.850         0     no  southeast   1629.83350
1336   21  female  25.800         0     no  southwest   2007.94500
1337   61  female  29.070         0    yes  northwest  29141.36030

[1338 rows x 7 columns]

In [17]:
x = df.drop(columns=['charges'])
y = df['charges']

In [18]:
from sklearn.preprocessing import LabelEncoder

In [19]:
lb = LabelEncoder()

In [20]:
x['sex'] = lb.fit_transform(df['sex'])
x['smoker'] = lb.fit_transform(df['smoker'])
x['region'] = lb.fit_transform(df['region'])

In [21]:
from sklearn.model_selection import train_test_split

In [22]:
x_train,x_test,y_train,y_test = train_test_split(x,y,test_size=0.2,random_state=42)

In [23]:
from sklearn.ensemble import RandomForestRegressor

In [24]:
dt = RandomForestRegressor()

In [25]:
dt.fit(x_train,y_train)

RandomForestRegressor()

In [26]:
y_pred = dt.predict(x_test)

In [27]:
from sklearn.metrics import r2_score

In [28]:
r2_score(y_test,y_pred)

0.8639194978261554

In [29]:
cf = pd.read_csv(r"D:\py_machine_learning\datasets\covid_toy - covid_toy.csv")
cf

    age  gender  fever   cough       city has_covid
0    60    Male  103.0    Mild    Kolkata        No
1    27    Male  100.0    Mild      Delhi       Yes
2    42    Male  101.0    Mild      Delhi        No
3    31  Female   98.0    Mild    Kolkata        No
4    65  Female  101.0    Mild     Mumbai        No
..  ...     ...    ...     ...        ...       ...
95   12  Female  104.0    Mild  Bangalore        No
96   51  Female  101.0  Strong    Kolkata       Yes
97   20  Female  101.0    Mild  Bangalore        No
98    5  Female   98.0  Strong     Mumbai        No
99   10  Female   98.0  Strong    Kolkata       Yes

[100 rows x 6 columns]

In [30]:
cf['fever'] = cf['fever'].fillna(cf['fever'].mean())

In [31]:
lb = LabelEncoder()

In [32]:
cf['gender'] = lb.fit_transform(cf['gender'])
cf['cough'] = lb.fit_transform(cf['cough'])
cf['city'] = lb.fit_transform(cf['city'])

In [33]:
x = cf.drop(columns=['has_covid'])
y = cf['has_covid']

In [34]:
x_train,x_test,y_train,y_test = train_test_split(x,y,test_size=0.2,random_state=42)

In [35]:
from sklearn.ensemble import RandomForestClassifier

In [36]:
rf = RandomForestClassifier()

In [37]:
rf.fit(x_train,y_train)

RandomForestClassifier()

In [38]:
y_pred = rf.predict(x_test)

In [39]:
from sklearn.metrics import accuracy_score

In [40]:
accuracy_score(y_test,y_pred)

0.55