In [15]:
import pandas as pd

In [16]:
df = pd.read_csv(r"D:\py_machine_learning\datasets\covid_toy - covid_toy.csv")
df

    age  gender  fever   cough       city has_covid
0    60    Male  103.0    Mild    Kolkata        No
1    27    Male  100.0    Mild      Delhi       Yes
2    42    Male  101.0    Mild      Delhi        No
3    31  Female   98.0    Mild    Kolkata        No
4    65  Female  101.0    Mild     Mumbai        No
..  ...     ...    ...     ...        ...       ...
95   12  Female  104.0    Mild  Bangalore        No
96   51  Female  101.0  Strong    Kolkata       Yes
97   20  Female  101.0    Mild  Bangalore        No
98    5  Female   98.0  Strong     Mumbai        No
99   10  Female   98.0  Strong    Kolkata       Yes

[100 rows x 6 columns]

In [17]:
df.isnull().sum()

age           0
gender        0
fever        10
cough         0
city          0
has_covid     0
dtype: int64

In [18]:
df['fever'] = df['fever'].fillna(df['fever'].mean())

In [19]:
df['gender'] = df['gender'].map({"Male":0,"Female":1})
df['cough'] = df['cough'].map({"Mild":0,"Strong":1})

In [20]:
df = df.drop(columns=['city'])

In [21]:
x = df.drop(columns=['has_covid'])
y = df['has_covid']

In [22]:
from sklearn.model_selection import train_test_split

In [23]:
x_train,x_test,y_train,y_test = train_test_split(x,y,test_size=0.2,random_state=42)

In [24]:
from sklearn.preprocessing import StandardScaler

In [25]:
sc = StandardScaler()

In [26]:
x_train_sc = sc.fit_transform(x_train)

In [27]:
x_train_new = pd.DataFrame(x_train_sc,columns=x_train.columns)

In [29]:
import numpy as np

In [30]:
np.round(x_train_new.describe(),2)

         age  gender  fever  cough
count  80.00   80.00  80.00  80.00
mean   -0.00   -0.00  -0.00  -0.00
std     1.01    1.01   1.01   1.01
min    -1.56   -1.19  -1.56  -0.82
25%    -0.94   -1.19  -0.51  -0.82
50%    -0.04    0.84   0.01  -0.82
75%     0.91    0.84   0.53   1.22
max     1.69    0.84   1.57   1.22